version: '2'
services:
    nginx:
      image: nginx
      privileged: true
      links:
        - web-client
        - data-store
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt:/etc/letsencrypt
      ports:
        - "80:80"
        - "443:443"

    data-store:
      build: ./services/data-store
      links:
        - rdbMaster
      depends_on:
        - rdbMaster
      ports:
        - "8080:80"
      working_dir: /home/docker/workplace/data-store

    web-client:
      build: ./services/web-client
      working_dir: /home/docker/workplace/web-client
      volumes:
        - ./services/web-client/fe/dist:/home/docker/workplace/web-client/fe/dist

    rdbMaster:
      image: rethinkdb
      ports:
        - "18080:8080"
      volumes:
        - ./_db:/data

